### ISSUE TITLE
Extend gray color all the way to the left

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/courtformsonline.org#1]
will need a new container for the left pane of the hero

**Comment by nonprofittechy** [comment]
Quick note to check on later--I think I solved this by just not dividing the top hero area into 2. Need to check.

**Comment by KindBill** [comment]
![Screenshot_4_16_24__9_12 AM](https://github.com/SuffolkLITLab/courtformsonline.org/assets/61289898/bef5a16d-8d3f-446b-adac-022e777e018a)

**Comment by KindBill** [comment]
No longer an issue.
