### ISSUE TITLE
Copy over the Spot integration from the massaccess repo

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/courtformsonline.org#10]
Currently on CourtFormsOnline.org there's a JavaScript that interacts with Spot. We should replicate that on the new courtformsonline.org

Can copy from the massaccess repo?

**Comment by nonprofittechy** [comment]
Here's the MassAccess repo: https://github.com/SuffolkLITLab/massaccess/

looks like the most work is done in make_query, which is in this file: https://github.com/SuffolkLITLab/massaccess/blob/master/core_assets/js_bin/test_train.js

That file is pretty long but we probably don't need all of it; it has a bunch of hardcoded HTML which is probably fine to start, but we'll want to at least do things like remove the hardcoded styles relatively soon (But maybe that's not MVP).

**Comment by KindBill** [comment]
Notes from our scoping call last week: https://www.notion.so/kindsystems/Scoping-Session-2024-04-19-fadbb0c36f47475cb834f212fd8503d9?pvs=4#bc23ef12fd9f41eb954f49629ec787c3

**Takeaways:**
1. There's a recommendation we made in our notes on how to display the category results of the Spot API.
2. We defaulted to showing all categories for now even if the category is empty.
