### ISSUE TITLE
For interview forms, URL should default to start

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/courtformsonline.org#11]

**Comment by KindBill** [comment]
![image](https://github.com/SuffolkLITLab/courtformsonline.org/assets/61289898/fa96d59d-d72d-4fae-bb73-ec6f6c9c942f)

**Comment by KindBill** [comment]
![image](https://github.com/SuffolkLITLab/courtformsonline.org/assets/61289898/fde7d5e4-b4a7-4450-bd3f-32714f64d18d)

**Comment by KindBill** [comment]
Decision during scoping session 4/19/24: Keep as start

**Comment by KindBill** [comment]
### User Story
As a developer, I want to keep using `start` in the URL for the interview forms, so that it's consistent.

---

**Comment by KindBill** [comment]
Josh will pick this one up.
