### ISSUE TITLE
Fix rounding of 1 2 3 icons

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/courtformsonline.org#2]
![image](https://github.com/SuffolkLITLab/courtformsonline.org/assets/7645641/f645514b-51e0-489b-994f-a94208e7e8fb)

**Comment by nonprofittechy** [comment]
Same issue with the topic cards. They are stretched vertically:

![image](https://github.com/SuffolkLITLab/courtformsonline.org/assets/7645641/4fe74731-6a86-4b0e-8dc4-ea5ab051953a)

**Comment by KindBill** [comment]
This has been fixed and resolved by Quinten.
