### ISSUE TITLE
"Show all categories" should be expanded by default and look like a button

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/courtformsonline.org#33]
![image](https://github.com/SuffolkLITLab/courtformsonline.org/assets/7645641/da956ad0-1f08-4358-87a0-7484da7ff434)

If there is anything in "Other", it should be shown. If we do end up somehow with too many top level categories, the "Show all" link should be a clear interactable element.

**Comment by samglover** [comment]
Does this still apply? I don't think there is a **Show all categories** link on [the new version of CFO](https://projects.suffolklitlab.org/courtformsonline.org/).

**Comment by samglover** [comment]
This doesn't seem to apply anymore. Closing as not planned.
