### ISSUE TITLE
Consider changing the font to Atkinson Hyperlegible

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/courtformsonline.org#73]
After reading through the [Neurodiversity Design System website](https://neurodiversity.design/principles/font/), I think it might be worth changing to Atkinson Hyperlegible, a font designed around accessibility by the [Braille Institute](https://www.brailleinstitute.org/freefont/). It is also [available on Google Fonts](https://fonts.google.com/specimen/Atkinson+Hyperlegible?query=hyperlegible).

If we do make this change, it would make sense to change the font on the [Document Assembly Line documentation website](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation), too. And it also might make sense to add it to the [Assembly Line tools](https://github.com/SuffolkLITLab/docassemble-AssemblyLine), at least as an option.

**Comment by samglover** [comment]
There is also an npm package, [@fontsource/atkinson-hyperlegible](https://www.npmjs.com/package/@fontsource/atkinson-hyperlegible).

**Comment by nonprofittechy** [comment]
Looks good to me!
