### ISSUE TITLE
Connect to Google Analytics & Search Console

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/courtformsonline.org#76]
I realize there are privacy implications, but I think the old [@SuffolkLITLab/massaccess](https://github.com/SuffolkLITLab/massaccess) website had Google Analytics. And since these forms/interviews are only effective if people can find them, we need to keep an eye on traffic and search indexing.

@colarusso & @nonprofittechy: Any thoughts or caveats before I submit a PR with the Google Analytics and Search Console code?

**Comment by nonprofittechy** [comment]
I would see what other analytics options we have. GA4 is much less useful than the old Google Analytics, and we weren't exactly making full use of it.

**Comment by nonprofittechy** [comment]
Maybe https://www.cloudflare.com/web-analytics/ will work for us?

**Comment by samglover** [comment]
True. We really only need to see visitors, landing pages, and pageviews over time, so I'll look for alternatives.

Google Search Console is pretty important, but I don't think there are the same privacy implications since we just need to [verify ownership](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#verification) in order to use it.

**Comment by samglover** [comment]
I was able to enable Cloudflare analytics and verified Google Search Console with a TXT DNS record, so we're all set!
