### ISSUE TITLE
Don't direct people to invalid URLs

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/courtformsonline.org#86]
If the metadata doesn't contain a valid URL, we shouldn't let people click on it.

Example: the Appeal or Stay Your Eviction help URL is "n/a"

![image](https://github.com/user-attachments/assets/b9125860-60b2-46ea-9574-5b248af494e4)

Since we're automating this landing page, we should consider adding a bit of data validation.

**Comment by samglover** [comment]
Huh, it looks like [someone did enter "n/a"](https://github.com/SuffolkLITLab/docassemble-MotionToStayEviction/blob/1b397b34fb7016591b2155dd6ded2554d10aa219/docassemble/MotionToStayEviction/data/questions/SP6A.yml#L59) in the metadata for that form. Validating for URLs is definitely worthwhile for these.
